### ISSUE TITLE
Fetch gets recognized as untagged IMAP response

### ISSUE THREAD

**Issue by vanBonzen** [jgosmann/dmarc-metrics-exporter#29] opened 2022-08-10 14:11 UTC
Hey,

we currently experience the problem, that our fetched messages get recognized as untagged IMAP responses. The verbose debug log states the following: 
![grafik](https://user-images.githubusercontent.com/12358706/183922894-fb64aa55-64eb-4d8d-8b20-1d18e308b893.png)

We are using a Office365 inbox.

Thank you in advance!

Kind regards
vanBonzen

**Comment by jgosmann** [comment] 2022-08-10 14:43
I won't have time to look into this until at least the middle of next week.

**Comment by jgosmann** [comment] 2022-08-20 17:30
I hope that this problem is fixed by #30. Could you try out that branch?

I would also appreciate if you could provide a full log line of the IMAP response (they are cut off in the screenshot). It would allow me to better understand the problem. You may redact any potentially sensitive content from the email body that will be probably be in there (also shortening the email body should be fine if it is very long, I'm mainly interested in what comes after that).

**Comment by jgosmann** [comment] 2022-09-24 17:24
I'm assuming that the issue is solved. If not feel free to reopen the issue with additional details.

**Closed** 2022-09-24 17:24 UTC
